console.log(process.env);
/*
{
  ALLUSERSPROFILE: 'C:\\ProgramData',
  APPDATA: 'C:\\Users\\dahuyou\\AppData\\Roaming',
  APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL: 'true',
  CHROME_CRASHPAD_PIPE_NAME: '\\\\.\\pipe\\crashpad_5892_DDJZDHPKNCDIKVGD',
  CommonProgramFiles: 'C:\\Program Files\\Common Files',
  'CommonProgramFiles(x86)': 'C:\\Program Files (x86)\\Common Files',
  CommonProgramW6432: 'C:\\Program Files\\Common Files',
  COMPUTERNAME: 'DAHUYOUのLENOVO',
  ComSpec: 'C:\\WINDOWS\\system32\\cmd.exe',
  DriverData: 'C:\\Windows\\System32\\Drivers\\DriverData',
  FPS_BROWSER_APP_PROFILE_STRING: 'Internet Explorer',
  FPS_BROWSER_USER_PROFILE_STRING: 'Default',
  HOMEDRIVE: 'C:',
  HOMEPATH: '\\Users\\dahuyou',
  LOCALAPPDATA: 'C:\\Users\\dahuyou\\AppData\\Local',
  LOGONSERVER: '\\\\DAHUYOUのLENOVO',
  NODE_PATH: 'C:\\Program Files\\nodejs',
  NUMBER_OF_PROCESSORS: '8',
  OneDrive: 'C:\\Users\\dahuyou\\OneDrive',
  OneDriveConsumer: 'C:\\Users\\dahuyou\\OneDrive',
  ORIGINAL_XDG_CURRENT_DESKTOP: 'undefined',
  OS: 'Windows_NT',
  Path: 'C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\软件\\Git\\cmd;C:\\Program Files\\nodejs;C:\\Program Files\\nodejs;C:\\Users\\dahuyou\\AppData\\Roaming\\npm;C:\\Program Files (x86)\\NetSarang\\Xshell 7\\;C:\\Program Files (x86)\\NetSarang\\Xftp 7\\;C:\\Users\\dahuyou\\AppData\\Roaming\\npm\\vue.ps1;C:\\Users\\dahuyou\\AppData\\Local\\Microsoft\\WindowsApps;C:\\软件\\vscode\\bin;"C:\\Users\\dahuyou\\AppData\\Roaming\\npm;C:\\Program Files\\nodejs;";C:\\Users\\dahuyou\\AppData\\Roaming\\npm\\vue.ps1;',
  PATHEXT: '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL',
  PROCESSOR_ARCHITECTURE: 'AMD64',
  PROCESSOR_IDENTIFIER: 'Intel64 Family 6 Model 140 Stepping 1, GenuineIntel',
  PROCESSOR_LEVEL: '6',
  PROCESSOR_REVISION: '8c01',
  ProgramData: 'C:\\ProgramData',
  ProgramFiles: 'C:\\Program Files',
  'ProgramFiles(x86)': 'C:\\Program Files (x86)',
  ProgramW6432: 'C:\\Program Files',
  PROMPT: '$P$G',
  PSModulePath: 'C:\\Users\\dahuyou\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules',
  PUBLIC: 'C:\\Users\\Public',
  SESSIONNAME: 'Console',
  SystemDrive: 'C:',
  SystemRoot: 'C:\\WINDOWS',
  TEMP: 'C:\\Users\\dahuyou\\AppData\\Local\\Temp',
  TMP: 'C:\\Users\\dahuyou\\AppData\\Local\\Temp',
  USERDOMAIN: 'DAHUYOUのLENOVO',
  USERDOMAIN_ROAMINGPROFILE: 'DAHUYOUのLENOVO',
  USERNAME: 'dahuyou',
  USERPROFILE: 'C:\\Users\\dahuyou',
  windir: 'C:\\WINDOWS',
  ZES_ENABLE_SYSMAN: '1',
  TERM_PROGRAM: 'vscode',
  TERM_PROGRAM_VERSION: '1.61.1',
  LANG: 'zh_CN.UTF-8',
  COLORTERM: 'truecolor',
  VSCODE_GIT_IPC_HANDLE: '\\\\.\\pipe\\vscode-git-876444f289-sock',
  GIT_ASKPASS: 'c:\\软件\\vscode\\resources\\app\\extensions\\git\\dist\\askpass.sh',
  VSCODE_GIT_ASKPASS_NODE: 'C:\\软件\\vscode\\Code.exe',
  VSCODE_GIT_ASKPASS_MAIN: 'c:\\软件\\vscode\\resources\\app\\extensions\\git\\dist\\askpass-main.js'
}
*/
console.log(process.env.NODE_PATH); // => C:\Program Files\nodejs